# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            I am Thunder Shiviah.
tagline:          
description:      'math, data, and connections'
url:              https://ThunderShiviah.github.io
baseurl:          '/'
paginate:         5

author:
  name:           'Thunder Shiviah'
  url:            https://twitter.com/tshiviah

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/ThunderShiviah
