# Site settings
title: Thunder Shiviah
#email: 
#description: > # this means to ignore newlines until "baseurl:"
    
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http:thundershiviah.github.io" # the base hostname & protocol for your site
twitter_username: tshiviah
github_username:  thundershiviah
#linkedin_username: Thunder Shiviah


# Build settings
markdown: kramdown
